### ISSUE TITLE
Create everything with the same package name

### ISSUE THREAD

**Issue by hekemp** [hekemp/CS2820#1]
Make sure that your code is contained in a package, and that package is "production".

**Comment by rschne** [comment]
I did this :)

**Comment by hekemp** [comment]
Belt: @melkeurti 

Inventory: @yunfjiang

Visualizer: @Xinglu Zhao

Shelf: @Qiansan

Order: @kanghyokyung

Please add your code for these classes and any related classes to the production package.

**Comment by hekemp** [comment]
Added the package line to the files that did not have the package line in it.
