### ISSUE TITLE
Bin and robot location needed

### ISSUE THREAD

**Issue by Xinglzhao** [hekemp/CS2820#7]
I need initialization of the robot location so that I can draw a robot at tick 0. And every tick there should be a method telling me where robot is and where is bin is on the belt area. Thank you. @rschne @melkeurti

**Comment by hekemp** [comment]
We decided that we are not using ticks and are instead using the queue method of keeping track of time. I think the best method for you to proceed is to query the items you need and ask their locations and then plot them.

**Comment by Qiansan** [comment]
I think using tick is the requirement. You can just use professor's code if you don't know how to do it.

**Comment by kanghyokyung** [comment]
Questions for Final Report (draft of ideas)

There will be one final assignment, related to the project, which is to write a "report" (really just answering some questions). Details about this assignment will be posted on the Monday of the last week of class. One purpose of this report is to help the Professor and TAs evaluate your contributions and participation in the group project. This report will be worth many points, so please start thinking about it now.

1. What works and what doesn't? In the Java code you submitted, what is properly functioning and what things were not completed at the time of the last commit. Where is your code? If it's all in the group CS2820 repo, fine, we will find it. But we won't know automatically to look elsewhere. How do you know what works and what doesn't? Did you write a test or was it tested by running the main program that ran the entire simulation? Would it be obvious to the TA how to run it and test it?

2. Did you make contributions outside of writing the code? Perhaps you helped debug, perhaps you co-authored parts that weren't in your original role, maybe you wrote about issues and closed them. In evaluating contributions, the TA won't know about meetings you had, verbal discussions, and other background activities: they will be looking at the repo and its history.

3. What interesting (perhaps creative) features did you design and implement? These could be interfaces, patterns, debugging and testing features which were valuable to the project.

4. Does your part of the project work with other parts of the group? For some parts, such as the order subsystem, there should be a "conversation" (in the form of interfaces and method calls) between the order part and the robot scheduler, or with the belt subsystem, and so forth. In the case of the visualizer, this part might get calls (ticks) from the master, then call other parts to get information. Did you work with other group members to negotiate how this works? Is evidence of this collaboration evident in the github repo?

5. How many lines of code did you write (approximately) and how many commits did you do? Of course the TA will be able to count (and also subtract, in the case of massive commits of the same code deleted and re-added), but as a doublecheck on your contribution, it will be useful to have your own view on your work, to validate what is found in the repo.

**Comment by rschne** [comment]
Not required. Only suggested.

**Comment by Xinglzhao** [comment]
Suggestions: there could be an Event class with each instance being an "event" and a priority queue from Java's library can contain many Event objects. One member of each Event should be which "task" to do when that Event is dequeued (perhaps Task is an interface with a fire(arg) method). When E.fire(arg) is called, the fire method can be from any of the other components, Floor, Belt, Inventory, Orders, Visualizer, or Robot -- probably most of these will need to implement the Task interface. Once fire(arg) is running, it can invoke Master.enqueue(newEvent) to add another (future) event to the Master's queue -- that implies that all the other components probably need to know about a Master object (perhaps as a parameter in their constructors). This can get confusing, so writing a picture of the interaction, perhaps using a Sequence diagram, is advisable.

The other thing Master will need is a "clock" which publishes "tick" continuously to all the other components (Floor, Belt, Inventory, etc). That means that all these other components will need to implement a Tickable interface so that Master can invoke O.tick(count) on each of them, where count is the clock value (which starts at zero).

**Comment by Qiansan** [comment]
But event queue seems like more complex than just using tick. Have asked professor about this?

**Comment by hekemp** [comment]
When we met and discussed it, we didn't think it was harder one way or the other and actually thought the queue would be the easier method.

Should we implement the tick method like you'd like to do, everyone would need to alter their code to remember what event happens at which part, as I would only pass in a tickable time. Considering that we haven't even gotten our initial event interface implemented, I'm not sure if we can get everyone to implement a new interface/system by the deadline with each part interacting with each other.

**Comment by hekemp** [comment]
I will set up another meeting sometime this week so we can discuss this/the code relationships and the other things we need before the 9th.

**Comment by Xinglzhao** [comment]
Could you explain the meaning of 

void performAction(String Method);
Event getEvent();
String getPara();

methods ? And is there a sample in all members work which implements event interface correctly?
