### ISSUE TITLE
Draft of ideas

### ISSUE THREAD

**Issue by kanghyokyung** [hekemp/CS2820#8]
Questions for Final Report (draft of ideas)

There will be one final assignment, related to the project, which is to write a "report" (really just answering some questions). Details about this assignment will be posted on the Monday of the last week of class. One purpose of this report is to help the Professor and TAs evaluate your contributions and participation in the group project. This report will be worth many points, so please start thinking about it now.

1. What works and what doesn't? In the Java code you submitted, what is properly functioning and what things were not completed at the time of the last commit. Where is your code? If it's all in the group CS2820 repo, fine, we will find it. But we won't know automatically to look elsewhere. How do you know what works and what doesn't? Did you write a test or was it tested by running the main program that ran the entire simulation? Would it be obvious to the TA how to run it and test it?

2. Did you make contributions outside of writing the code? Perhaps you helped debug, perhaps you co-authored parts that weren't in your original role, maybe you wrote about issues and closed them. In evaluating contributions, the TA won't know about meetings you had, verbal discussions, and other background activities: they will be looking at the repo and its history.

3. What interesting (perhaps creative) features did you design and implement? These could be interfaces, patterns, debugging and testing features which were valuable to the project.

4. Does your part of the project work with other parts of the group? For some parts, such as the order subsystem, there should be a "conversation" (in the form of interfaces and method calls) between the order part and the robot scheduler, or with the belt subsystem, and so forth. In the case of the visualizer, this part might get calls (ticks) from the master, then call other parts to get information. Did you work with other group members to negotiate how this works? Is evidence of this collaboration evident in the github repo?

5. How many lines of code did you write (approximately) and how many commits did you do? Of course the TA will be able to count (and also subtract, in the case of massive commits of the same code deleted and re-added), but as a doublecheck on your contribution, it will be useful to have your own view on your work, to validate what is found in the repo. 
-author prof Ted Herman-
Copied from Icon Discussion Object oriented Programming

**Comment by hekemp** [comment]
A quick question -- how is this an issue that we need to solve for this project? To my understanding, this is an individual report we have to fill out by the deadline...
