### ISSUE TITLE
Robot get path from floor.

### ISSUE THREAD

**Issue by Qiansan** [hekemp/CS2820#9]
Robot doesn't need to override the method from floor.
The method: getRoute() in floor should be directly used by robot. 
Like : Arraylist< Point> path = floor.getRoute(p1,p2); and the visualizer will need to get this list of point from you in order to print robot's path.
And I have a floor interface for you.

**Comment by Qiansan** [comment]
@rschne

**Comment by rschne** [comment]
I will work on this. Thanks!
